### ISSUE TITLE
./weathermap 

### ISSUE THREAD

**Issue by danogueira** [amousset/php-weathermap-zabbix-plugin#6]
I am trying to set up weathermap to Zabbix following this guide:
http://blog.51cto.com/luojinghappy/1845218

When I tried to execute ./weathermap program It shows me this error:

root@zabbix:/usr/share/zabbix/weathermap# ./weathermap --config configs/simple.conf
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /usr/share/php/Console/Getopt.php on line 135
WARNING: configs/simple.conf: RRD DS: Can't find RRDTOOL. Check line 29 of the 'weathermap' script.
RRD-based TARGETs will fail. [WMRRD02]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /usr/share/zabbix/weathermap/lib/SimpleZabbixApi.php:18
Stack trace:
#0 /usr/share/zabbix/weathermap/lib/SimpleZabbixApi.php(41): SimpleZabbixApi->jsonRequest(Array)
#1 /usr/share/zabbix/weathermap/lib/SimpleZabbixApi.php(56): SimpleZabbixApi->request('user.login', Array)
#2 /usr/share/zabbix/weathermap/lib/SimpleZabbixApi.php(9): SimpleZabbixApi->auth('weathermap', 'weathermap')
#3 /usr/share/zabbix/weathermap/lib/datasources/WeatherMapDataSource_zabbix.php(15): SimpleZabbixApi->__construct('http://192.168....', 'weathermap', 'weathermap')
#4 /usr/share/zabbix/weathermap/lib/Weathermap.class.php(754): WeatherMapDataSource_zabbix->Init(Object(WeatherMap))
#5 /usr/share/zabbix/weathermap/lib/Weathermap.class.php(870): WeatherMap->DatasourceInit()
#6 /usr/share/zabbix/weathermap/weathermap(241): WeatherMap->ReadData()
#7 {main}
  thrown in /usr/share/zabbix/weathermap/lib/SimpleZabbixApi.php on line 18
root@zabbix:/usr/share/zabbix/weathermap#

Where am I going wrong?

**Comment by danogueira** [comment]
I have installed php7.2-curl package.
Now I got other error:

root@zabbix:/usr/share/zabbix/weathermap# ./weathermap --config configs/simple.conf --htmloutput test01.html
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /usr/share/php/Console/Getopt.php on line 135
WARNING: configs/simple.conf: RRD DS: Can't find RRDTOOL. Check line 29 of the 'weathermap' script.
RRD-based TARGETs will fail. [WMRRD02]
WARNING: configs/simple.conf: ProcessTargets: LINK node1-node2, target: zabbix:name:Switch_L3:GigabitEthernet0/0-IN:GigabitEthernet0/0-OUT on config line 77 of configs/simple.conf was recognised as a valid TARGET by a plugin that is unable to run (WeatherMapDataSource_zabbix) [WMWARN07]
PHP Warning:  A non-numeric value encountered in /usr/share/zabbix/weathermap/lib/Weathermap.class.php on line 960
PHP Warning:  A non-numeric value encountered in /usr/share/zabbix/weathermap/lib/Weathermap.class.php on line 961
root@zabbix:/usr/share/zabbix/weathermap#

**Comment by danogueira** [comment]
957                                                                 if($multiply != 1) {
 958                                                                         wm_debug("Pre-multiply: $in $out\n");
 959
 960                                                                         $in = $multiply*$in;
 961                                                                         $out = $multiply*$out;
 962
 963                                                                         wm_debug("Post-multiply: $in $out\n");
 964                                                                 }

**Comment by danogueira** [comment]
My config file:

root@zabbix:/usr/share/zabbix/weathermap# cat configs/teste.conf
FONTDEFINE 100 docs/example/Vera.ttf 10

BACKGROUND images/bw_gradient_1024.png
WIDTH 950
HEIGHT 625
HTMLSTYLE overlib
KEYFONT 100
TITLE test
TIMEPOS 746 17 Created: %b %d %Y %H:%M:%S

KEYPOS DEFAULT 10 11 Traffic Load
KEYTEXTCOLOR 0 0 0
KEYOUTLINECOLOR 0 0 0
KEYBGCOLOR 255 255 255
BGCOLOR 255 255 255
TITLECOLOR 0 0 0
TIMECOLOR 0 0 0
SCALE DEFAULT 0 0   192 192 192
SCALE DEFAULT 0 1   255 255 255
SCALE DEFAULT 1 10   140 0 255
SCALE DEFAULT 10 25   32 32 255
SCALE DEFAULT 25 40   0 192 255
SCALE DEFAULT 40 55   0 240 0
SCALE DEFAULT 55 70   240 240 0
SCALE DEFAULT 70 85   255 192 0
SCALE DEFAULT 85 100   255 0 0

SET nowarn_clipping 1

# End of global section


# General configuration
SET zabbix_user weathermap
SET zabbix_password weathermap
SET zabbix_url http:///192.168.66.4/api_jsonrpc.php
SET post_zabbix_graph_link enabled

# Graph configuration
SET post_zabbix_graphs 1
SET post_zabbix_graph_link 1
SET post_zabbix_graph_base_url https://192.168.66.4/zabbix
SET post_zabbix_graph_width 420
SET post_zabbix_graph_height 150
SET post_zabbix_graph_period 86400

# sample nodes
NODE switch-1
        LABEL Switch_L3
        OVERLIBGRAPH zabbix:name:Switch_L3:CPU_usage
        ICON images/WorkgroupSwitch.png
        POSITION 200 280

NODE switch-2
        LABEL Switch_L2
        OVERLIBGRAPH zabbix:name:Switch_L2:CPU_usage
        ICON images/WorkgroupSwitch.png
        POSITION 760 280

# sample link
LINK switch-1-switch-2
        OVERLIBGRAPH zabbix:name:Switch_L3:GigabitEthernet0/1
        TARGET zabbix:itemid:Switch_L3:28549:28576
        NODES switch-1 switch-2
root@zabbix:/usr/share/zabbix/weathermap#
